apiVersion: v1
kind: Service
metadata:
  name: staging-svc
  labels:
    color: green
spec:
  ports:
    - name: web
      port: 8080
      targetPort: 80
  selector:
    target: green-dep
  type: LoadBalancer 